### ISSUE TITLE
Forums

### ISSUE THREAD

**Issue by ahmed9018** [osateam/ssonline#1]
Forums have been down for like 2 days now coming up for like 5 minutes then going back down again.

**Comment by m7md-ae** [comment]
This is now fixed.

If it still doesn't work, please clear your cache:
- Mac - https://support.apple.com/en-ae/HT202516
- Windows - https://technet.microsoft.com/en-us/library/cc781949(v=ws.10).aspx

**Comment by mohdalali** [comment]
This is now fixed.

If it still doesn't work, please clear your cache:
- Mac - https://support.apple.com/en-ae/HT202516
- Windows - https://technet.microsoft.com/en-us/library/cc781949(v=ws.10).aspx
