### ISSUE TITLE
Uploading Forum Avatar

### ISSUE THREAD

**Issue by Hyperguyalex** [osateam/ssonline#2]
I am unable to upload an avatar to my Forum Profile. Is there any way I can upload one without it saying it's too big for the server to upload?

I have tried even the smallest of images and the outcome has been the same.

Thanks.

**Comment by Ashlyn-OSA** [comment]
This was an error caused by not having enough space on our old server, should work okay now ;)

**Comment by Ashlyn-OSA** [comment]
not* ooops.
