### ISSUE TITLE
Private Messaging On Forums

### ISSUE THREAD

**Issue by Spokedia** [osateam/ssonline#3]
![000](https://cloud.githubusercontent.com/assets/13308161/8642753/4e502daa-28f7-11e5-9d08-4f1722cf7cf5.PNG)

When I try to PM someone, and hit submit, or view previous PMs this is always the case. Thank you!

**Comment by Ashlyn-OSA** [comment]
Should be fixed sine we switched to a new server! Reopen a thread if this persists :)
