### ISSUE TITLE
no Room Control rank on the rank list

### ISSUE THREAD

**Issue by Jakeedog** [osateam/ssonline#5]
Title is pretty self explanatory, there isn't a Room Control rank on the rank list, nor is there a page for Room Control members like there was on the previous site. I'll attach the list of current RC members.
XXbloodxxangel
.:kamo45:.
ExploreJamaica
Jakeedog
Dolphins
Lachie53ALT.
xMark.
Apocalyptoz
Kenilworth
ahmed9018
Dimult
richmond757
cassbee
DarUmJeitoBR
metalrobert
Rimulose
jessikachu
DinkerDan

**Comment by genrbr** [comment]
There is a page for Room Control. I don't know whether you mean it's not listed, but if not listed, I will be sure to fix it when I'm back.

Regardless of a site update, pages will always remain the same as it was before. You can access the Room Control page by entering this URL: habboss.com/rc
