### ISSUE TITLE
Problem with homebutton.

### ISSUE THREAD

**Issue by Odinor** [osateam/ssonline#6]
Hello,
http://prntscr.com/7u3ofn : when I click on the home button on the forums.

**Comment by genrbr** [comment]
This issue should be fixed now and was only temporarily. For any future preferences, the home button on forum will just lead to the forum index.

Thanks for the report

**Comment by genrbr** [comment]
This issue should be fixed now and was only temporarily. For any future preferences, the home button on forum will just lead to the forum index.

Thanks for the report
